#pragma once
#include <VTFLib.h>

typedef unsigned int __uint32_t;
typedef __uint32_t uint32_t;

constexpr struct TextureFlag
{
	uint32_t flag;
	const char *name;
} TEXTURE_FLAGS[] = {
	{ TEXTUREFLAGS_POINTSAMPLE, "Point Sample" },
	{ TEXTUREFLAGS_TRILINEAR, "Trilinear" },
	{ TEXTUREFLAGS_CLAMPS, "Clamp S" },
	{ TEXTUREFLAGS_CLAMPT, "Clamp T" },
	{ TEXTUREFLAGS_CLAMPU, "Clamp U" },
	{ TEXTUREFLAGS_ANISOTROPIC, "Anisotropic" },
	{ TEXTUREFLAGS_HINT_DXT5, "Hint DXT5" },
	{ TEXTUREFLAGS_SRGB, "sRGB" },
	{ TEXTUREFLAGS_DEPRECATED_NOCOMPRESS, "Nocompress (Deprecated)" },
	{ TEXTUREFLAGS_NORMAL, "Normal" },
	{ TEXTUREFLAGS_NOMIP, "No MIP" },
	{ TEXTUREFLAGS_NOLOD, "No LOD" },
	{ TEXTUREFLAGS_MINMIP, "Min Mip" },
	{ TEXTUREFLAGS_PROCEDURAL, "Procedural" },
	{ TEXTUREFLAGS_ONEBITALPHA, "One-bit Alpha" },
	{ TEXTUREFLAGS_EIGHTBITALPHA, "Eight-bit Alpha" },
	{ TEXTUREFLAGS_ENVMAP, "Envmap" },
	{ TEXTUREFLAGS_RENDERTARGET, "Render Target" },
	{ TEXTUREFLAGS_DEPTHRENDERTARGET, "Depth Render Target" },
	{ TEXTUREFLAGS_NODEBUGOVERRIDE, "No Debug Override" },
	{ TEXTUREFLAGS_SINGLECOPY, "Single Copy" },
	{ TEXTUREFLAGS_DEPRECATED_ONEOVERMIPLEVELINALPHA, "One Over Mip Level Linear Alpha (Deprecated)" },
	{ TEXTUREFLAGS_DEPRECATED_PREMULTCOLORBYONEOVERMIPLEVEL, "Pre-multiply Colors by One Over Mip Level (Deprecated)" },
	{ TEXTUREFLAGS_DEPRECATED_NORMALTODUDV, "Normal To DuDv" },
	{ TEXTUREFLAGS_DEPRECATED_ALPHATESTMIPGENERATION, "Alpha Test Mip Generation (Deprecated)" },
	{ TEXTUREFLAGS_NODEPTHBUFFER, "No Depth Buffer" },
	{ TEXTUREFLAGS_DEPRECATED_NICEFILTERED, "Nice Filtered (Deprecated)" },
	{ TEXTUREFLAGS_VERTEXTEXTURE, "Vertex Texture" },
	{ TEXTUREFLAGS_SSBUMP, "SSBump" },
	{ TEXTUREFLAGS_DEPRECATED_UNFILTERABLE_OK, "Unfilterable OK (Deprecated)" },
	{ TEXTUREFLAGS_BORDER, "Border" },
	{ TEXTUREFLAGS_DEPRECATED_SPECVAR_RED, "Specvar Red (Deprecated)" },
	{ TEXTUREFLAGS_DEPRECATED_SPECVAR_ALPHA, "Specvar Alpha (Deprecated)" },
};

static inline constexpr struct
{
	VTFImageFormat format;
	const char *name;
} IMAGE_FORMATS[] = {
	{ IMAGE_FORMAT_RGBA8888, "RGBA8888" },
	{ IMAGE_FORMAT_ABGR8888, "ABGR8888" },
	{ IMAGE_FORMAT_RGB888, "RGB888" },
	{ IMAGE_FORMAT_BGR888, "BGR888" },
	{ IMAGE_FORMAT_RGB565, "RGB565" },
	{ IMAGE_FORMAT_I8, "I8" },
	{ IMAGE_FORMAT_IA88, "IA88" },
	{ IMAGE_FORMAT_P8, "P8" },
	{ IMAGE_FORMAT_A8, "A8" },
	{ IMAGE_FORMAT_RGB888_BLUESCREEN, "RGB888_BLUESCREEN" },
	{ IMAGE_FORMAT_BGR888_BLUESCREEN, "BGR888_BLUESCREEN" },
	{ IMAGE_FORMAT_ARGB8888, "ARGB8888" },
	{ IMAGE_FORMAT_BGRA8888, "BGRA8888" },
	{ IMAGE_FORMAT_DXT1, "DXT1" },
	{ IMAGE_FORMAT_DXT3, "DXT3" },
	{ IMAGE_FORMAT_DXT5, "DXT5" },
	{ IMAGE_FORMAT_BGRX8888, "BGRX8888" },
	{ IMAGE_FORMAT_BGR565, "BGR565" },
	{ IMAGE_FORMAT_BGRX5551, "BGRX5551" },
	{ IMAGE_FORMAT_BGRA4444, "BGRA4444" },
	{ IMAGE_FORMAT_DXT1_ONEBITALPHA, "DXT1_ONEBITALPHA" },
	{ IMAGE_FORMAT_BGRA5551, "BGRA5551" },
	{ IMAGE_FORMAT_UV88, "UV88" },
	{ IMAGE_FORMAT_UVWQ8888, "UVWQ8888" },
	{ IMAGE_FORMAT_RGBA16161616F, "RGBA16161616F" },
	{ IMAGE_FORMAT_RGBA16161616, "RGBA16161616" },
	{ IMAGE_FORMAT_UVLX8888, "UVLX8888" },
	{ IMAGE_FORMAT_R32F, "R32F" },
	{ IMAGE_FORMAT_RGB323232F, "RGB323232F" },
	{ IMAGE_FORMAT_RGBA32323232F, "RGBA32323232F" },
	{ IMAGE_FORMAT_NV_DST16, "NV_DST16" },
	{ IMAGE_FORMAT_NV_DST24, "NV_DST24" },
	{ IMAGE_FORMAT_NV_INTZ, "NV_INTZ" },
	{ IMAGE_FORMAT_NV_RAWZ, "NV_RAWZ" },
	{ IMAGE_FORMAT_ATI_DST16, "ATI_DST16" },
	{ IMAGE_FORMAT_ATI_DST24, "ATI_DST24" },
	{ IMAGE_FORMAT_NV_NULL, "NV_NULL" },
	{ IMAGE_FORMAT_ATI2N, "ATI2N" },
	{ IMAGE_FORMAT_ATI1N, "ATI1N" },
};

static inline constexpr const char *FILE_FIELDS[] = { "Size", "Version", "Compression Level" };

static inline constexpr const char *INFO_FIELDS[] = {
	"Width", "Height", "Depth", "Frames", "Faces", "Mips", "Reflectivity" };
