name: Build
on:
  push:
    branches: [ rework-vtfpp ]
  workflow_dispatch: # nothing here


env:
  BUILD_DIR: '${{github.workspace}}/build'
  QT_VERSION: '6.8.0'
  QT_MODULES: 'qtimageformats'

jobs:
  build-linux:
    strategy:
      matrix:
        build_type: [ Debug, Release ]
        target: [ Source, StrataSource ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: ${{env.QT_VERSION}}
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          modules: ${{env.QT_MODULES}}
          dir: '${{github.workspace}}/libs/Qt'
          cache: true

      - name: Configure CMake
        if: ${{matrix.target == 'StrataSource'}}
        run: cmake -G "Unix Makefiles" -B build -DCHAOS_INITIATIVE=ON -DCOMPRESSVTF=ON -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DQT_BASEDIR='${{github.workspace}}/libs/Qt/Qt/${{env.QT_VERSION}}/gcc_64'

      - name: Configure CMake
        if: ${{matrix.target == 'Source'}}
        run: cmake -G "Unix Makefiles" -B build -DCOMPRESSVTF=ON -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DQT_BASEDIR='${{github.workspace}}/libs/Qt/Qt/${{env.QT_VERSION}}/gcc_64'


      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Fixup Binaries
        run: |
          sudo apt install chrpath
          
          # runpath cleanup for the Qt binaries. These are (mostly) wrong, leading to crashes
          for f in ${{env.BUILD_DIR}}/*.so*; do
            echo "Fixing $f..."
            chrpath -r '$ORIGIN' "$f"
          done
          for f in ${{env.BUILD_DIR}}/*/*.so*; do
            echo "Fixing $f..."
            chrpath -r '$ORIGIN/..' "$f"
          done

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vtf-edit-revitalized-linux-${{matrix.build_type}}-${{matrix.target}}
          path: |
            ${{github.workspace}}/build/VTF_Edit_Revitalized
            ${{github.workspace}}/build/imageformats/*.so*
            ${{github.workspace}}/build/platforms/*.so*
            ${{github.workspace}}/build/*.so*
            ${{github.workspace}}/build/xcbglintegrations/*.so*

  build-msvc:
    strategy:
      matrix:
        build_type: [ Debug, Release ]
        target: [ Source, StrataSource ]
    runs-on: windows-2019
    defaults:
      run:
        shell: cmd
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Install Qt6
        uses: jurplel/install-qt-action@v4
        with:
          aqtversion: '==3.1.*'
          dir: '${{github.workspace}}/libs/Qt'
          version: ${{env.QT_VERSION}}
          arch: win64_msvc2025_64
          modules: ${{env.QT_MODULES}}
          cache: true

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        if: ${{matrix.target == 'StrataSource'}}
        env:
          CMAKE_PREFIX_PATH: ${{env.Qt6_Dir}}
        run: cmake -G "Ninja" -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCOMPRESSVTF=ON -DCHAOS_INITIATIVE=ON -DQT_BASEDIR=${{github.workspace}}\libs\Qt\Qt\${{env.QT_VERSION}}\msvc2019_64

      - name: Configure CMake
        if: ${{matrix.target == 'Source'}}
        env:
          CMAKE_PREFIX_PATH: ${{env.Qt6_Dir}}
        run: cmake -G "Ninja" -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCOMPRESSVTF=ON -DQT_BASEDIR=${{github.workspace}}\libs\Qt\Qt\${{env.QT_VERSION}}\msvc2019_64


      - name: Build
        run: cmake --build build --config ${{matrix.build_type}}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vtf-edit-revitalized-windows-${{matrix.build_type}}-${{matrix.target}}
          path: |
            ${{github.workspace}}\build\*.exe
            ${{github.workspace}}\build\*.dll
            ${{github.workspace}}\build\platforms\*.dll
            ${{github.workspace}}\build\tls\*.dll
            ${{github.workspace}}\build\imageformats\*.dll
            

